[functions.send-class-reminders]
verify_jwt = false

[functions.privacy-policy]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.account-deletion-request]
verify_jwt = false
