import { StyleSheet } from 'react-native';

import { ucapsaBrand } from '../../constants/brand';

export const styles = StyleSheet.create({
  screenContent: { position: 'relative' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 14, paddingHorizontal: 2 },
  identityRow: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 10 },
  identityCopy: { flex: 1, minWidth: 0 },
  markWrap: { width: 42, height: 42, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  markWrapPremium: { position: 'relative', borderWidth: 1, borderColor: ucapsaBrand.colors.premiumBorderStrong, backgroundColor: ucapsaBrand.colors.premiumSurface },
  mark: { width: 35, height: 35 },
  crownBadge: { position: 'absolute', top: -7, right: -7, width: 21, height: 21, borderRadius: 11, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: ucapsaBrand.colors.premiumBorderStrong, backgroundColor: ucapsaBrand.colors.premiumSurface },
  headerEyebrow: { fontSize: 9, lineHeight: 11, fontWeight: '900', letterSpacing: 1.05 },
  headerTitle: { marginTop: 1, fontSize: 22, lineHeight: 25, fontWeight: '900', letterSpacing: -0.35 },
  headerDetail: { marginTop: 2, fontSize: 11, lineHeight: 15, fontWeight: '800' },
  accountButton: { width: 42, height: 42, borderRadius: 15, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  guestCard: { flexDirection: 'row', gap: 12, borderRadius: 22, borderWidth: 1, padding: 15, marginBottom: 16 },
  guestIcon: { width: 48, height: 48, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  guestBody: { flex: 1, gap: 6 },
  guestTitle: { fontSize: 17, lineHeight: 21, fontWeight: '900' },
  guestText: { fontSize: 12, lineHeight: 18, fontWeight: '700' },
  guestActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 5 },
  primaryButton: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 14, paddingHorizontal: 13 },
  primaryButtonText: { fontSize: 12, fontWeight: '900' },
  secondaryButton: { minHeight: 42, borderWidth: 1, borderRadius: 14, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 13 },
  secondaryButtonText: { fontSize: 12, fontWeight: '900' },
  loadingRow: { minHeight: 72, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 },
  loadingText: { fontSize: 12, fontWeight: '800' },
  stateStrip: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderRadius: 18, padding: 12, marginBottom: 12 },
  stateCopy: { flex: 1 },
  stateTitle: { fontSize: 13, fontWeight: '900' },
  stateText: { marginTop: 2, fontSize: 11, lineHeight: 16, fontWeight: '700' },
  iconButton: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  syncStrip: { flexDirection: 'row', alignItems: 'center', gap: 7, borderWidth: 1, borderRadius: 14, paddingHorizontal: 10, paddingVertical: 8, marginBottom: 10 },
  syncText: { flex: 1, fontSize: 10, lineHeight: 14, fontWeight: '800' },
  nextCard: { minHeight: 102, borderRadius: 24, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 12 },
  nextIcon: { width: 50, height: 50, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  nextCopy: { flex: 1, minWidth: 0, gap: 2 },
  nextEyebrow: { fontSize: 9, lineHeight: 12, fontWeight: '900', letterSpacing: 1.05, opacity: 0.84 },
  nextTitle: { fontSize: 20, lineHeight: 24, fontWeight: '900', letterSpacing: -0.25 },
  nextDetail: { fontSize: 11, lineHeight: 16, fontWeight: '800', opacity: 0.86 },
  programCard: { overflow: 'hidden', borderWidth: 1, borderRadius: 22, marginBottom: 12 },
  programMain: { padding: 13 },
  programTop: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  programIcon: { width: 46, height: 46, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  programCopy: { flex: 1, minWidth: 0 },
  programEyebrow: { fontSize: 9, lineHeight: 12, fontWeight: '900', letterSpacing: 0.95 },
  programTitle: { marginTop: 1, fontSize: 19, lineHeight: 23, fontWeight: '900', letterSpacing: -0.22 },
  programMeta: { marginTop: 2, fontSize: 11, lineHeight: 15, fontWeight: '700' },
  attendanceBlock: { marginTop: 12, gap: 6 },
  attendanceLabels: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  attendanceTitle: { fontSize: 11, fontWeight: '800' },
  attendanceValue: { fontSize: 11, fontWeight: '900' },
  progressTrack: { height: 7, borderRadius: 999, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999 },
  practiceSummary: { minHeight: 54, borderTopWidth: 1, flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8, paddingHorizontal: 13, paddingVertical: 10 },
  practiceSummaryItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  practiceSummaryText: { fontSize: 10, fontWeight: '900' },
  practiceWeekText: { flex: 1, minWidth: 100, fontSize: 10, lineHeight: 14, fontWeight: '700' },
  activityCard: { borderWidth: 1, borderRadius: 22, padding: 13, marginBottom: 14 },
  activityHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  activityEyebrow: { fontSize: 8, lineHeight: 11, fontWeight: '900', letterSpacing: 0.9 },
  activityTitle: { marginTop: 1, fontSize: 18, lineHeight: 22, fontWeight: '900' },
  metricsRow: { marginTop: 12, paddingTop: 11, borderTopWidth: 1, flexDirection: 'row', alignItems: 'stretch' },
  metricInline: { flex: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', gap: 2, paddingHorizontal: 5, paddingVertical: 3 },
  metricValue: { color: ucapsaBrand.colors.text, fontSize: 20, lineHeight: 23, fontWeight: '900' },
  metricLabel: { color: ucapsaBrand.colors.muted, textAlign: 'center', fontSize: 9, lineHeight: 12, fontWeight: '800' },
  metricDivider: { width: 1, marginVertical: 3, opacity: 0.8 },
  competitionHomeCard: { minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderRadius: 20, padding: 12, marginBottom: 14 },
  competitionHomeIcon: { width: 44, height: 44, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  competitionHomeCopy: { flex: 1, minWidth: 0 },
  competitionHomeEyebrow: { fontSize: 8, lineHeight: 11, fontWeight: '900', letterSpacing: 0.9 },
  competitionHomeTitle: { marginTop: 1, fontSize: 15, lineHeight: 19, fontWeight: '900' },
  competitionHomeDetail: { marginTop: 2, fontSize: 10, lineHeight: 14, fontWeight: '700' },
  contextBlock: { gap: 8, marginBottom: 14 },
  contextHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  contextSectionTitle: { fontSize: 17, lineHeight: 21, fontWeight: '900' },
  contextLink: { fontSize: 10, fontWeight: '900' },
  contextStrip: { minHeight: 74, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderRadius: 18, padding: 11 },
  contextIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  contextCopy: { flex: 1, minWidth: 0 },
  contextEyebrow: { fontSize: 8, lineHeight: 11, fontWeight: '900', letterSpacing: 0.85 },
  contextTitle: { marginTop: 1, fontSize: 14, lineHeight: 18, fontWeight: '900' },
  contextDetail: { marginTop: 2, fontSize: 10, lineHeight: 14, fontWeight: '700' },
  noticeLinkOnly: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, marginBottom: 8 },
  noticeLinkOnlyText: { fontSize: 11, fontWeight: '900' },
});
