alter table public.achievement_definitions add constraint achievement_definitions_color_key_check CHECK (color_key = ANY (ARRAY['red'::text, 'blue'::text, 'yellow'::text, 'green'::text, 'purple'::text, 'gray'::text]));
alter table public.achievement_definitions add constraint achievement_definitions_pkey PRIMARY KEY (code);
alter table public.admin_audit_logs add constraint admin_audit_logs_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES auth.users(id);
alter table public.admin_audit_logs add constraint admin_audit_logs_pkey PRIMARY KEY (id);
alter table public.announcements add constraint announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.announcements add constraint announcements_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL;
alter table public.announcements add constraint announcements_pkey PRIMARY KEY (id);
alter table public.attendance_qr_codes add constraint attendance_qr_codes_after_window_check CHECK (window_after_minutes >= 0 AND window_after_minutes <= 360);
alter table public.attendance_qr_codes add constraint attendance_qr_codes_before_window_check CHECK (window_before_minutes >= 0 AND window_before_minutes <= 180);
alter table public.attendance_qr_codes add constraint attendance_qr_codes_pkey PRIMARY KEY (program_code);
alter table public.attendance_qr_codes add constraint attendance_qr_codes_program_check CHECK (program_code = ANY (ARRAY['puppy'::text, 'comandos'::text, 'member'::text]));
alter table public.attendance_qr_codes add constraint attendance_qr_codes_token_key UNIQUE (token);
alter table public.attendance_qr_codes add constraint attendance_qr_codes_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.attendance_qr_codes add constraint attendance_qr_codes_version_check CHECK (version >= 1);
alter table public.dog_documents add constraint dog_documents_dates_check CHECK (issued_on IS NULL OR expires_on IS NULL OR expires_on >= issued_on);
alter table public.dog_documents add constraint dog_documents_dog_id_fkey FOREIGN KEY (dog_id) REFERENCES dogs(id) ON DELETE CASCADE;
alter table public.dog_documents add constraint dog_documents_path_not_blank CHECK (btrim(storage_path) <> ''::text);
alter table public.dog_documents add constraint dog_documents_pkey PRIMARY KEY (id);
alter table public.dog_documents add constraint dog_documents_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.dog_documents add constraint dog_documents_status_check CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]));
alter table public.dog_documents add constraint dog_documents_type_not_blank CHECK (btrim(document_type) <> ''::text);
alter table public.dog_documents add constraint dog_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.dogs add constraint dogs_name_not_blank CHECK (btrim(name) <> ''::text);
alter table public.dogs add constraint dogs_pkey PRIMARY KEY (id);
alter table public.dogs add constraint dogs_sex_check CHECK (sex IS NULL OR (sex = ANY (ARRAY['female'::text, 'male'::text, 'unknown'::text])));
alter table public.dogs add constraint dogs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.dogs add constraint dogs_weight_non_negative CHECK (weight_kg IS NULL OR weight_kg >= 0::numeric);
alter table public.events add constraint events_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.events add constraint events_end_after_start CHECK (end_date IS NULL OR end_date >= start_date);
alter table public.events add constraint events_pkey PRIMARY KEY (id);
alter table public.events add constraint events_repeat_interval_days_check CHECK (repeat_interval_days IS NULL OR repeat_interval_days >= 1 AND repeat_interval_days <= 365);
alter table public.events add constraint events_repeat_limit_check CHECK (repeat_limit >= 1 AND repeat_limit <= 10);
alter table public.events add constraint events_repeat_type_check CHECK (repeat_type = ANY (ARRAY['none'::text, 'daily'::text, 'weekly'::text, 'biweekly'::text, 'monthly'::text, 'custom_days'::text]));
alter table public.feature_flags add constraint feature_flags_code_check CHECK (code = ANY (ARRAY['exams'::text, 'dog_profiles'::text, 'dog_documents'::text]));
alter table public.feature_flags add constraint feature_flags_pkey PRIMARY KEY (code);
alter table public.feature_flags add constraint feature_flags_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.member_visits add constraint member_visits_membership_id_fkey FOREIGN KEY (membership_id) REFERENCES memberships(id) ON DELETE SET NULL;
alter table public.member_visits add constraint member_visits_pkey PRIMARY KEY (id);
alter table public.member_visits add constraint member_visits_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.member_visits add constraint member_visits_source_check CHECK (source = ANY (ARRAY['qr_member'::text, 'admin_manual'::text]));
alter table public.member_visits add constraint member_visits_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.membership_billing_profiles add constraint membership_billing_amount_check CHECK (amount >= 0::numeric);
alter table public.membership_billing_profiles add constraint membership_billing_dates_check CHECK (ends_on IS NULL OR ends_on >= starts_on);
alter table public.membership_billing_profiles add constraint membership_billing_due_day_check CHECK (due_day >= 1 AND due_day <= 31);
alter table public.membership_billing_profiles add constraint membership_billing_profiles_membership_id_fkey FOREIGN KEY (membership_id) REFERENCES memberships(id) ON DELETE CASCADE;
alter table public.membership_billing_profiles add constraint membership_billing_profiles_pkey PRIMARY KEY (membership_id);
alter table public.membership_billing_profiles add constraint membership_billing_profiles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.membership_delete_requests add constraint membership_delete_requests_pkey PRIMARY KEY (id);
alter table public.membership_delete_requests add constraint membership_delete_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.membership_delete_requests add constraint membership_delete_requests_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.membership_delete_requests add constraint membership_delete_requests_status_check CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]));
alter table public.memberships add constraint memberships_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id);
alter table public.memberships add constraint memberships_current_payment_status_check CHECK (current_payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'not_required'::text]));
alter table public.memberships add constraint memberships_end_after_start CHECK (start_date IS NULL OR end_date IS NULL OR end_date >= start_date);
alter table public.memberships add constraint memberships_member_number_key UNIQUE (member_number);
alter table public.memberships add constraint memberships_pkey PRIMARY KEY (id);
alter table public.memberships add constraint memberships_qr_token_key UNIQUE (qr_token);
alter table public.memberships add constraint memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.memberships add constraint memberships_user_id_key UNIQUE (user_id);
alter table public.notification_campaigns add constraint notification_campaigns_audience_check CHECK (audience = ANY (ARRAY['public'::text, 'clients'::text, 'members'::text, 'admins'::text]));
alter table public.notification_campaigns add constraint notification_campaigns_category_check CHECK (category = ANY (ARRAY['announcements_events'::text, 'classes'::text, 'membership'::text, 'achievements'::text]));
alter table public.notification_campaigns add constraint notification_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.notification_campaigns add constraint notification_campaigns_pkey PRIMARY KEY (id);
alter table public.notification_campaigns add constraint notification_campaigns_status_check CHECK (status = ANY (ARRAY['draft'::text, 'sending'::text, 'sent'::text, 'partial_failed'::text, 'failed'::text, 'no_targets'::text]));
alter table public.notification_class_cancellation_locks add constraint notification_class_cancellation_locks_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES notification_campaigns(id) ON DELETE SET NULL;
alter table public.notification_class_cancellation_locks add constraint notification_class_cancellation_locks_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES program_enrollments(id) ON DELETE CASCADE;
alter table public.notification_class_cancellation_locks add constraint notification_class_cancellation_locks_pkey PRIMARY KEY (id);
alter table public.notification_class_cancellation_locks add constraint notification_class_cancellation_locks_program_id_fkey FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE;
alter table public.notification_class_cancellation_locks add constraint notification_class_cancellation_locks_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES program_schedules(id) ON DELETE CASCADE;
alter table public.notification_class_cancellation_locks add constraint notification_class_cancellation_locks_status_check CHECK (status = ANY (ARRAY['locked'::text, 'sent'::text, 'skipped'::text, 'failed'::text]));
alter table public.notification_class_cancellation_locks add constraint notification_class_cancellation_locks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.notification_class_reminder_locks add constraint notification_class_reminder_locks_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES notification_campaigns(id) ON DELETE SET NULL;
alter table public.notification_class_reminder_locks add constraint notification_class_reminder_locks_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES program_enrollments(id) ON DELETE CASCADE;
alter table public.notification_class_reminder_locks add constraint notification_class_reminder_locks_pkey PRIMARY KEY (id);
alter table public.notification_class_reminder_locks add constraint notification_class_reminder_locks_program_id_fkey FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE;
alter table public.notification_class_reminder_locks add constraint notification_class_reminder_locks_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES program_schedules(id) ON DELETE CASCADE;
alter table public.notification_class_reminder_locks add constraint notification_class_reminder_locks_status_check CHECK (status = ANY (ARRAY['locked'::text, 'sent'::text, 'skipped'::text, 'failed'::text]));
alter table public.notification_class_reminder_locks add constraint notification_class_reminder_locks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.notification_deliveries add constraint notification_deliveries_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES notification_campaigns(id) ON DELETE CASCADE;
alter table public.notification_deliveries add constraint notification_deliveries_pkey PRIMARY KEY (id);
alter table public.notification_deliveries add constraint notification_deliveries_status_check CHECK (status = ANY (ARRAY['queued'::text, 'sent'::text, 'error'::text]));
alter table public.notification_deliveries add constraint notification_deliveries_token_id_fkey FOREIGN KEY (token_id) REFERENCES notification_tokens(id) ON DELETE SET NULL;
alter table public.notification_deliveries add constraint notification_deliveries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.notification_preferences add constraint notification_preferences_pkey PRIMARY KEY (user_id);
alter table public.notification_preferences add constraint notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.notification_tokens add constraint notification_tokens_expo_push_token_key UNIQUE (expo_push_token);
alter table public.notification_tokens add constraint notification_tokens_pkey PRIMARY KEY (id);
alter table public.notification_tokens add constraint notification_tokens_platform_check CHECK (platform = ANY (ARRAY['ios'::text, 'android'::text, 'web'::text, 'unknown'::text]));
alter table public.notification_tokens add constraint notification_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.payment_obligations add constraint payment_obligations_amount_check CHECK (amount >= 0::numeric);
alter table public.payment_obligations add constraint payment_obligations_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.payment_obligations add constraint payment_obligations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.payment_obligations add constraint payment_obligations_currency_check CHECK (currency ~ '^[A-Z]{3}$'::text);
alter table public.payment_obligations add constraint payment_obligations_membership_id_fkey FOREIGN KEY (membership_id) REFERENCES memberships(id) ON DELETE SET NULL;
alter table public.payment_obligations add constraint payment_obligations_period_check CHECK (period_start IS NULL OR period_end IS NULL OR period_end >= period_start);
alter table public.payment_obligations add constraint payment_obligations_pkey PRIMARY KEY (id);
alter table public.payment_obligations add constraint payment_obligations_source_check CHECK (source = ANY (ARRAY['manual'::text, 'recurring'::text, 'service'::text, 'purchase'::text]));
alter table public.payment_obligations add constraint payment_obligations_type_check CHECK (obligation_type = ANY (ARRAY['membership'::text, 'program'::text, 'service'::text, 'purchase'::text, 'other'::text]));
alter table public.payment_obligations add constraint payment_obligations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.payment_settings add constraint payment_settings_clabe_check CHECK (clabe IS NULL OR clabe ~ '^[0-9]{18}$'::text);
alter table public.payment_settings add constraint payment_settings_pkey PRIMARY KEY (id);
alter table public.payment_settings add constraint payment_settings_singleton CHECK (id = 1);
alter table public.payment_settings add constraint payment_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.payments add constraint payments_amount_non_negative CHECK (amount >= 0::numeric);
alter table public.payments add constraint payments_membership_id_fkey FOREIGN KEY (membership_id) REFERENCES memberships(id) ON DELETE SET NULL;
alter table public.payments add constraint payments_obligation_id_fkey FOREIGN KEY (obligation_id) REFERENCES payment_obligations(id) ON DELETE SET NULL;
alter table public.payments add constraint payments_pkey PRIMARY KEY (id);
alter table public.payments add constraint payments_registered_by_fkey FOREIGN KEY (registered_by) REFERENCES auth.users(id);
alter table public.payments add constraint payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.practice_sessions add constraint practice_sessions_difficulty_check CHECK (difficulty = ANY (ARRAY['easy'::text, 'good'::text, 'hard'::text]));
alter table public.practice_sessions add constraint practice_sessions_dog_id_fkey FOREIGN KEY (dog_id) REFERENCES dogs(id) ON DELETE SET NULL;
alter table public.practice_sessions add constraint practice_sessions_duration_check CHECK (duration_seconds IS NULL OR duration_seconds >= 0);
alter table public.practice_sessions add constraint practice_sessions_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES program_enrollments(id) ON DELETE SET NULL;
alter table public.practice_sessions add constraint practice_sessions_pkey PRIMARY KEY (id);
alter table public.practice_sessions add constraint practice_sessions_time_check CHECK (completed_at >= started_at);
alter table public.practice_sessions add constraint practice_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_avatar_color_format_check CHECK (avatar_color ~ '^#[0-9A-Fa-f]{6}$'::text);
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_user_id_key UNIQUE (user_id);
alter table public.program_attendances add constraint program_attendances_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES program_enrollments(id) ON DELETE CASCADE;
alter table public.program_attendances add constraint program_attendances_pkey PRIMARY KEY (id);
alter table public.program_attendances add constraint program_attendances_session_id_fkey FOREIGN KEY (session_id) REFERENCES program_sessions(id) ON DELETE RESTRICT;
alter table public.program_class_cancellations add constraint program_class_cancellations_announcement_id_fkey FOREIGN KEY (announcement_id) REFERENCES announcements(id) ON DELETE SET NULL;
alter table public.program_class_cancellations add constraint program_class_cancellations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.program_class_cancellations add constraint program_class_cancellations_pkey PRIMARY KEY (id);
alter table public.program_class_cancellations add constraint program_class_cancellations_restored_by_fkey FOREIGN KEY (restored_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.program_class_cancellations add constraint program_class_cancellations_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES program_schedules(id) ON DELETE CASCADE;
alter table public.program_enrollments add constraint program_enrollments_attendances_count_check CHECK (attendances_count >= 0);
alter table public.program_enrollments add constraint program_enrollments_card_dates_check CHECK (card_started_on IS NULL OR card_expires_on IS NULL OR card_expires_on >= card_started_on);
alter table public.program_enrollments add constraint program_enrollments_dog_id_fkey FOREIGN KEY (dog_id) REFERENCES dogs(id) ON DELETE SET NULL;
alter table public.program_enrollments add constraint program_enrollments_pkey PRIMARY KEY (id);
alter table public.program_enrollments add constraint program_enrollments_program_id_fkey FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE RESTRICT;
alter table public.program_enrollments add constraint program_enrollments_program_level_check CHECK (program_level = ANY (ARRAY['base'::text, 'principiante'::text, 'medio'::text, 'avanzado'::text]));
alter table public.program_enrollments add constraint program_enrollments_qr_token_key UNIQUE (qr_token);
alter table public.program_enrollments add constraint program_enrollments_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES program_schedules(id) ON DELETE RESTRICT;
alter table public.program_enrollments add constraint program_enrollments_status_check CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'cancelled'::text]));
alter table public.program_exams add constraint program_exams_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES program_enrollments(id) ON DELETE CASCADE;
alter table public.program_exams add constraint program_exams_pkey PRIMARY KEY (id);
alter table public.program_exams add constraint program_exams_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.program_exams add constraint program_exams_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.program_exams add constraint program_exams_status_check CHECK (status = ANY (ARRAY['requested'::text, 'scheduled'::text, 'completed'::text, 'approved'::text, 'failed'::text, 'cancelled'::text]));
alter table public.program_exams add constraint program_exams_target_level_check CHECK (target_level IS NULL OR (target_level = ANY (ARRAY['base'::text, 'principiante'::text, 'medio'::text, 'avanzado'::text])));
alter table public.program_schedule_versions add constraint program_schedule_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.program_schedule_versions add constraint program_schedule_versions_day_check CHECK (day_of_week >= 0 AND day_of_week <= 6);
alter table public.program_schedule_versions add constraint program_schedule_versions_pkey PRIMARY KEY (id);
alter table public.program_schedule_versions add constraint program_schedule_versions_range_check CHECK (effective_to IS NULL OR effective_to >= effective_from);
alter table public.program_schedule_versions add constraint program_schedule_versions_repeat_check CHECK (repeat_type = ANY (ARRAY['weekly'::text, 'biweekly'::text]));
alter table public.program_schedule_versions add constraint program_schedule_versions_retired_by_fkey FOREIGN KEY (retired_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.program_schedule_versions add constraint program_schedule_versions_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES program_schedules(id) ON DELETE CASCADE;
alter table public.program_schedules add constraint program_schedules_day_of_week_check CHECK (day_of_week >= 0 AND day_of_week <= 6);
alter table public.program_schedules add constraint program_schedules_pkey PRIMARY KEY (id);
alter table public.program_schedules add constraint program_schedules_program_id_fkey FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE;
alter table public.program_schedules add constraint program_schedules_repeat_type_check CHECK (repeat_type = ANY (ARRAY['weekly'::text, 'biweekly'::text]));
alter table public.program_sessions add constraint program_sessions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.program_sessions add constraint program_sessions_pkey PRIMARY KEY (id);
alter table public.program_sessions add constraint program_sessions_schedule_date_unique UNIQUE (schedule_id, session_date);
alter table public.program_sessions add constraint program_sessions_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES program_schedules(id) ON DELETE RESTRICT;
alter table public.program_sessions add constraint program_sessions_status_check CHECK (status = ANY (ARRAY['scheduled'::text, 'completed'::text, 'cancelled'::text]));
alter table public.programs add constraint programs_code_check CHECK (code = ANY (ARRAY['puppy'::text, 'comandos'::text]));
alter table public.programs add constraint programs_code_key UNIQUE (code);
alter table public.programs add constraint programs_color_key_check CHECK (color_key = ANY (ARRAY['red'::text, 'blue'::text, 'yellow'::text, 'green'::text, 'purple'::text, 'gray'::text]));
alter table public.programs add constraint programs_pkey PRIMARY KEY (id);
alter table public.programs add constraint programs_required_attendances_check CHECK (required_attendances > 0);
alter table public.user_achievements add constraint user_achievements_achievement_code_fkey FOREIGN KEY (achievement_code) REFERENCES achievement_definitions(code) ON DELETE RESTRICT;
alter table public.user_achievements add constraint user_achievements_awarded_by_fkey FOREIGN KEY (awarded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.user_achievements add constraint user_achievements_pkey PRIMARY KEY (id);
alter table public.user_achievements add constraint user_achievements_user_id_achievement_code_key UNIQUE (user_id, achievement_code);
alter table public.user_achievements add constraint user_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX audit_logs_admin_user_idx ON public.admin_audit_logs USING btree (admin_user_id);
CREATE INDEX announcements_audience_idx ON public.announcements USING btree (audience);
CREATE INDEX announcements_color_priority_idx ON public.announcements USING btree (color_key, priority, announcement_date, created_at);
CREATE INDEX announcements_created_at_idx ON public.announcements USING btree (created_at DESC);
CREATE INDEX announcements_event_id_idx ON public.announcements USING btree (event_id);
CREATE INDEX announcements_visibility_idx ON public.announcements USING btree (audience, is_published, archived_at, created_at DESC);
CREATE INDEX dog_documents_dog_idx ON public.dog_documents USING btree (dog_id);
CREATE INDEX dog_documents_status_idx ON public.dog_documents USING btree (status, expires_on);
CREATE INDEX dogs_user_id_idx ON public.dogs USING btree (user_id);
CREATE INDEX events_audience_idx ON public.events USING btree (audience);
CREATE INDEX events_calendar_visibility_idx ON public.events USING btree (audience, is_published, archived_at, start_date);
CREATE INDEX events_color_priority_idx ON public.events USING btree (color_key, priority, start_date);
CREATE INDEX events_recurrence_idx ON public.events USING btree (repeat_type, repeat_limit, start_date);
CREATE INDEX events_recurrence_key_idx ON public.events USING btree (recurrence_key);
CREATE INDEX events_start_date_idx ON public.events USING btree (start_date);
CREATE INDEX events_visibility_idx ON public.events USING btree (audience, is_published, archived_at, start_date);
CREATE INDEX member_visits_date_idx ON public.member_visits USING btree (visit_date DESC);
CREATE INDEX member_visits_membership_visited_idx ON public.member_visits USING btree (membership_id, visited_at DESC);
CREATE INDEX member_visits_user_visited_idx ON public.member_visits USING btree (user_id, visited_at DESC);
CREATE INDEX membership_delete_requests_membership_idx ON public.membership_delete_requests USING btree (membership_id);
CREATE INDEX membership_delete_requests_status_idx ON public.membership_delete_requests USING btree (status, requested_at);
CREATE INDEX memberships_admin_status_idx ON public.memberships USING btree (status, current_payment_status, end_date, created_at DESC);
CREATE INDEX memberships_member_number_idx ON public.memberships USING btree (member_number);
CREATE UNIQUE INDEX memberships_member_number_unique_idx ON public.memberships USING btree (member_number) WHERE (member_number IS NOT NULL);
CREATE INDEX memberships_payment_status_idx ON public.memberships USING btree (current_payment_status);
CREATE INDEX memberships_qr_token_idx ON public.memberships USING btree (qr_token);
CREATE UNIQUE INDEX memberships_qr_token_unique_idx ON public.memberships USING btree (qr_token);
CREATE INDEX memberships_status_idx ON public.memberships USING btree (status);
CREATE INDEX memberships_user_id_idx ON public.memberships USING btree (user_id);
CREATE INDEX notification_campaigns_created_at_idx ON public.notification_campaigns USING btree (created_at DESC);
CREATE INDEX notification_campaigns_created_by_idx ON public.notification_campaigns USING btree (created_by);
CREATE INDEX notification_campaigns_status_idx ON public.notification_campaigns USING btree (status);
CREATE UNIQUE INDEX notification_class_cancellation_locks_unique ON public.notification_class_cancellation_locks USING btree (enrollment_id, schedule_id, cancellation_date);
CREATE UNIQUE INDEX notification_class_reminder_locks_unique ON public.notification_class_reminder_locks USING btree (enrollment_id, schedule_id, class_date, reminder_type);
CREATE INDEX notification_deliveries_campaign_id_idx ON public.notification_deliveries USING btree (campaign_id);
CREATE INDEX notification_deliveries_status_idx ON public.notification_deliveries USING btree (status);
CREATE INDEX notification_deliveries_user_id_idx ON public.notification_deliveries USING btree (user_id);
CREATE INDEX notification_tokens_active_idx ON public.notification_tokens USING btree (is_active) WHERE (is_active = true);
CREATE INDEX notification_tokens_user_id_idx ON public.notification_tokens USING btree (user_id);
CREATE INDEX payment_obligations_membership_idx ON public.payment_obligations USING btree (membership_id, period_start);
CREATE INDEX payment_obligations_user_due_idx ON public.payment_obligations USING btree (user_id, due_date);
CREATE INDEX payments_membership_id_idx ON public.payments USING btree (membership_id);
CREATE INDEX payments_obligation_idx ON public.payments USING btree (obligation_id);
CREATE INDEX payments_status_idx ON public.payments USING btree (status);
CREATE INDEX payments_user_id_idx ON public.payments USING btree (user_id);
CREATE INDEX payments_user_id_paid_at_idx ON public.payments USING btree (user_id, paid_at DESC);
CREATE INDEX practice_sessions_dog_completed_idx ON public.practice_sessions USING btree (dog_id, completed_at DESC);
CREATE INDEX practice_sessions_enrollment_completed_idx ON public.practice_sessions USING btree (enrollment_id, completed_at DESC);
CREATE UNIQUE INDEX practice_sessions_user_client_event_uidx ON public.practice_sessions USING btree (user_id, client_event_id) WHERE (client_event_id IS NOT NULL);
CREATE INDEX practice_sessions_user_completed_idx ON public.practice_sessions USING btree (user_id, completed_at DESC);
CREATE INDEX profiles_deletion_requested_idx ON public.profiles USING btree (deletion_requested_at) WHERE (deletion_requested_at IS NOT NULL);
CREATE INDEX profiles_email_idx ON public.profiles USING btree (email);
CREATE INDEX profiles_role_idx ON public.profiles USING btree (role);
CREATE INDEX profiles_user_id_idx ON public.profiles USING btree (user_id);
CREATE UNIQUE INDEX program_attendances_enrollment_date_unique_idx ON public.program_attendances USING btree (enrollment_id, attendance_date);
CREATE INDEX program_attendances_enrollment_idx ON public.program_attendances USING btree (enrollment_id);
CREATE UNIQUE INDEX program_attendances_session_enrollment_unique_idx ON public.program_attendances USING btree (session_id, enrollment_id) WHERE (session_id IS NOT NULL);
CREATE INDEX program_attendances_session_idx ON public.program_attendances USING btree (session_id);
CREATE UNIQUE INDEX program_class_cancellations_active_unique ON public.program_class_cancellations USING btree (schedule_id, cancellation_date) WHERE (restored_at IS NULL);
CREATE INDEX program_class_cancellations_schedule_date_idx ON public.program_class_cancellations USING btree (schedule_id, cancellation_date);
CREATE INDEX program_enrollments_dog_idx ON public.program_enrollments USING btree (dog_id);
CREATE UNIQUE INDEX program_enrollments_program_card_unique_idx ON public.program_enrollments USING btree (program_id, lower(btrim(physical_card_number))) WHERE ((physical_card_number IS NOT NULL) AND (btrim(physical_card_number) <> ''::text));
CREATE INDEX program_enrollments_program_idx ON public.program_enrollments USING btree (program_id);
CREATE INDEX program_enrollments_schedule_idx ON public.program_enrollments USING btree (schedule_id);
CREATE INDEX program_enrollments_status_idx ON public.program_enrollments USING btree (status);
CREATE INDEX program_enrollments_user_idx ON public.program_enrollments USING btree (user_id);
CREATE INDEX program_exams_enrollment_idx ON public.program_exams USING btree (enrollment_id, requested_at DESC);
CREATE INDEX program_exams_status_idx ON public.program_exams USING btree (status, scheduled_at);
CREATE INDEX program_schedule_versions_lookup_idx ON public.program_schedule_versions USING btree (schedule_id, effective_from, effective_to) WHERE (retired_at IS NULL);
CREATE UNIQUE INDEX program_schedule_versions_schedule_from_unique ON public.program_schedule_versions USING btree (schedule_id, effective_from) WHERE (retired_at IS NULL);
CREATE UNIQUE INDEX program_schedules_program_name_idx ON public.program_schedules USING btree (program_id, name);
CREATE INDEX program_sessions_date_idx ON public.program_sessions USING btree (session_date, scheduled_start_time);
CREATE INDEX program_sessions_schedule_idx ON public.program_sessions USING btree (schedule_id, session_date);
CREATE INDEX user_achievements_code_idx ON public.user_achievements USING btree (achievement_code);
CREATE INDEX user_achievements_user_idx ON public.user_achievements USING btree (user_id);

