-- Triggers
CREATE TRIGGER set_announcements_updated_at BEFORE UPDATE ON announcements FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_attendance_qr_codes_updated_at BEFORE UPDATE ON attendance_qr_codes FOR EACH ROW EXECUTE FUNCTION set_config_updated_by();
CREATE TRIGGER set_dog_documents_updated_at BEFORE UPDATE ON dog_documents FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_dogs_updated_at BEFORE UPDATE ON dogs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_sync_program_enrollment_dog_name AFTER UPDATE OF name ON dogs FOR EACH ROW EXECUTE FUNCTION sync_program_enrollment_dog_name();
CREATE TRIGGER set_events_updated_at BEFORE UPDATE ON events FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_feature_flags_updated_at BEFORE UPDATE ON feature_flags FOR EACH ROW EXECUTE FUNCTION set_config_updated_by();
CREATE TRIGGER set_member_visits_updated_at BEFORE UPDATE ON member_visits FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_membership_billing_profiles_updated_at BEFORE UPDATE ON membership_billing_profiles FOR EACH ROW EXECUTE FUNCTION set_config_updated_by();
CREATE TRIGGER set_memberships_updated_at BEFORE UPDATE ON memberships FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_notification_campaigns_updated_at BEFORE UPDATE ON notification_campaigns FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();
CREATE TRIGGER set_notification_deliveries_updated_at BEFORE UPDATE ON notification_deliveries FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();
CREATE TRIGGER set_notification_preferences_updated_at BEFORE UPDATE ON notification_preferences FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();
CREATE TRIGGER set_notification_tokens_updated_at BEFORE UPDATE ON notification_tokens FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();
CREATE TRIGGER set_payment_obligations_updated_at BEFORE UPDATE ON payment_obligations FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_payment_settings_updated_at BEFORE UPDATE ON payment_settings FOR EACH ROW EXECUTE FUNCTION set_config_updated_by();
CREATE TRIGGER set_payments_updated_at BEFORE UPDATE ON payments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_validate_payment_obligation_owner BEFORE INSERT OR UPDATE OF obligation_id, user_id, membership_id ON payments FOR EACH ROW EXECUTE FUNCTION validate_payment_obligation_owner();
CREATE TRIGGER set_practice_sessions_updated_at BEFORE UPDATE ON practice_sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER prevent_unauthorized_profile_changes_trigger BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION prevent_unauthorized_profile_changes();
CREATE TRIGGER set_profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_program_attendances_updated_at BEFORE UPDATE ON program_attendances FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_program_attendances_refresh_progress AFTER INSERT OR DELETE OR UPDATE ON program_attendances FOR EACH ROW EXECUTE FUNCTION trg_refresh_program_enrollment_progress();
CREATE TRIGGER ensure_program_enrollment_dog_link BEFORE INSERT OR UPDATE OF user_id, dog_id, dog_name ON program_enrollments FOR EACH ROW EXECUTE FUNCTION ensure_program_enrollment_dog_link();
CREATE TRIGGER set_program_enrollments_updated_at BEFORE UPDATE ON program_enrollments FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_program_enrollment_card_validity BEFORE INSERT OR UPDATE OF started_at, card_started_on, card_expires_on ON program_enrollments FOR EACH ROW EXECUTE FUNCTION set_program_enrollment_card_validity();
CREATE TRIGGER trg_ucapsa_award_program_achievement AFTER INSERT OR UPDATE OF status ON program_enrollments FOR EACH ROW EXECUTE FUNCTION ucapsa_award_program_achievement();
CREATE TRIGGER set_program_exams_updated_at BEFORE UPDATE ON program_exams FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_program_exam_client_request_guard BEFORE INSERT ON program_exams FOR EACH ROW EXECUTE FUNCTION guard_program_exam_client_request();
CREATE TRIGGER set_program_sessions_updated_at BEFORE UPDATE ON program_sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

create event trigger ensure_rls on ddl_command_end when tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO') execute function public.rls_auto_enable();

-- RLS state
alter table public.achievement_definitions enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.announcements enable row level security;
alter table public.attendance_qr_codes enable row level security;
alter table public.dog_documents enable row level security;
alter table public.dogs enable row level security;
alter table public.events enable row level security;
alter table public.feature_flags enable row level security;
alter table public.member_visits enable row level security;
alter table public.membership_billing_profiles enable row level security;
alter table public.membership_delete_requests enable row level security;
alter table public.memberships enable row level security;
alter table public.notification_campaigns enable row level security;
alter table public.notification_class_cancellation_locks enable row level security;
alter table public.notification_class_reminder_locks enable row level security;
alter table public.notification_deliveries enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.notification_tokens enable row level security;
alter table public.payment_obligations enable row level security;
alter table public.payment_settings enable row level security;
alter table public.payments enable row level security;
alter table public.practice_sessions enable row level security;
alter table public.profiles enable row level security;
alter table public.program_attendances enable row level security;
alter table public.program_class_cancellations enable row level security;
alter table public.program_enrollments enable row level security;
alter table public.program_exams enable row level security;
alter table public.program_schedule_versions enable row level security;
alter table public.program_schedules enable row level security;
alter table public.program_sessions enable row level security;
alter table public.programs enable row level security;
alter table public.user_achievements enable row level security;

-- Policies
create policy achievement_definitions_admin_all on public.achievement_definitions as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy achievement_definitions_select_all on public.achievement_definitions as permissive for select to anon, authenticated using ((is_active = true));
create policy audit_logs_admin_insert on public.admin_audit_logs as permissive for insert to authenticated with check (is_admin());
create policy audit_logs_admin_select on public.admin_audit_logs as permissive for select to authenticated using (is_admin());
create policy announcements_admin_all on public.announcements as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy announcements_select_by_audience on public.announcements as permissive for select to anon, authenticated using (((is_published = true) AND (archived_at IS NULL) AND ((audience = 'public'::audience_type) OR ((auth.uid() IS NOT NULL) AND (audience = 'clients'::audience_type)) OR ((audience = 'members'::audience_type) AND has_active_membership()) OR ((audience = 'admins'::audience_type) AND is_admin()) OR is_admin())));
create policy attendance_qr_codes_admin_select on public.attendance_qr_codes as permissive for select to authenticated using (is_admin());
create policy dog_documents_admin_all on public.dog_documents as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy dog_documents_owner_insert_enabled on public.dog_documents as permissive for insert to authenticated with check ((is_feature_enabled('dog_profiles'::text) AND is_feature_enabled('dog_documents'::text) AND (status = 'pending'::text) AND (uploaded_by = auth.uid()) AND (reviewed_by IS NULL) AND (reviewed_at IS NULL) AND (rejection_reason IS NULL) AND (EXISTS (SELECT 1 FROM dogs d WHERE ((d.id = dog_documents.dog_id) AND (d.user_id = auth.uid()))))));
create policy dog_documents_owner_select_enabled on public.dog_documents as permissive for select to authenticated using ((is_feature_enabled('dog_profiles'::text) AND is_feature_enabled('dog_documents'::text) AND (EXISTS (SELECT 1 FROM dogs d WHERE ((d.id = dog_documents.dog_id) AND (d.user_id = auth.uid()))))));
create policy dogs_admin_all on public.dogs as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy dogs_owner_insert_enabled on public.dogs as permissive for insert to authenticated with check ((is_feature_enabled('dog_profiles'::text) AND (user_id = auth.uid())));
create policy dogs_owner_select_enabled on public.dogs as permissive for select to authenticated using ((is_feature_enabled('dog_profiles'::text) AND (user_id = auth.uid())));
create policy dogs_owner_update_enabled on public.dogs as permissive for update to authenticated using ((is_feature_enabled('dog_profiles'::text) AND (user_id = auth.uid()))) with check ((is_feature_enabled('dog_profiles'::text) AND (user_id = auth.uid())));
create policy events_admin_all on public.events as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy events_select_by_audience on public.events as permissive for select to anon, authenticated using (((is_published = true) AND (archived_at IS NULL) AND ((audience = 'public'::audience_type) OR ((auth.uid() IS NOT NULL) AND (audience = 'clients'::audience_type)) OR ((audience = 'members'::audience_type) AND has_active_membership()) OR ((audience = 'admins'::audience_type) AND is_admin()) OR is_admin())));
create policy feature_flags_select_authenticated on public.feature_flags as permissive for select to authenticated using (true);
create policy feature_flags_super_admin_update on public.feature_flags as permissive for update to authenticated using (is_super_admin()) with check (is_super_admin());
create policy member_visits_admin_all on public.member_visits as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy member_visits_own_select on public.member_visits as permissive for select to authenticated using (((user_id = auth.uid()) OR is_admin()));
create policy membership_billing_profiles_admin_all on public.membership_billing_profiles as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy membership_billing_profiles_select_own_or_admin on public.membership_billing_profiles as permissive for select to authenticated using ((is_admin() OR (EXISTS (SELECT 1 FROM memberships m WHERE ((m.id = membership_billing_profiles.membership_id) AND (m.user_id = auth.uid()))))));
create policy membership_delete_requests_admin_insert on public.membership_delete_requests as permissive for insert to authenticated with check (is_admin());
create policy membership_delete_requests_admin_select on public.membership_delete_requests as permissive for select to authenticated using (is_admin());
create policy membership_delete_requests_super_admin_update on public.membership_delete_requests as permissive for update to authenticated using (is_super_admin()) with check (is_super_admin());
create policy memberships_admin_insert on public.memberships as permissive for insert to authenticated with check (is_admin());
create policy memberships_admin_select on public.memberships as permissive for select to authenticated using (is_admin());
create policy memberships_admin_update on public.memberships as permissive for update to authenticated using (is_admin()) with check (is_admin());
create policy memberships_insert_own_pending on public.memberships as permissive for insert to authenticated with check (((user_id = auth.uid()) AND (status = 'pending'::membership_status)));
create policy memberships_select_own_or_admin on public.memberships as permissive for select to authenticated using (((user_id = auth.uid()) OR is_admin()));
create policy memberships_super_admin_delete on public.memberships as permissive for delete to authenticated using (is_super_admin());
create policy "Admins can read notification campaigns" on public.notification_campaigns as permissive for select to authenticated using (is_ucapsa_admin());
create policy notification_campaigns_admin_update on public.notification_campaigns as permissive for update to authenticated using (is_ucapsa_admin()) with check (is_ucapsa_admin());
create policy "Admins can read notification deliveries" on public.notification_deliveries as permissive for select to authenticated using (is_ucapsa_admin());
create policy "Users can insert own notification preferences" on public.notification_preferences as permissive for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users can read own notification preferences" on public.notification_preferences as permissive for select to authenticated using (((auth.uid() = user_id) OR is_ucapsa_admin()));
create policy "Users can update own notification preferences" on public.notification_preferences as permissive for update to authenticated using (((auth.uid() = user_id) OR is_ucapsa_admin())) with check (((auth.uid() = user_id) OR is_ucapsa_admin()));
create policy "Users can insert own notification tokens" on public.notification_tokens as permissive for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users can read own notification tokens" on public.notification_tokens as permissive for select to authenticated using (((auth.uid() = user_id) OR is_ucapsa_admin()));
create policy "Users can update own notification tokens" on public.notification_tokens as permissive for update to authenticated using (((auth.uid() = user_id) OR is_ucapsa_admin())) with check (((auth.uid() = user_id) OR is_ucapsa_admin()));
create policy payment_obligations_admin_all on public.payment_obligations as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy payment_obligations_select_own_or_admin on public.payment_obligations as permissive for select to authenticated using (((user_id = auth.uid()) OR is_admin()));
create policy payment_settings_admin_update on public.payment_settings as permissive for update to authenticated using (is_admin()) with check (is_admin());
create policy payment_settings_authenticated_select on public.payment_settings as permissive for select to authenticated using (((is_active = true) OR is_admin()));
create policy payments_admin_all on public.payments as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy payments_admin_delete on public.payments as permissive for delete to authenticated using (is_admin());
create policy payments_select_own_or_admin on public.payments as permissive for select to authenticated using (((user_id = auth.uid()) OR is_admin()));
create policy practice_sessions_own_insert on public.practice_sessions as permissive for insert to authenticated with check (((user_id = auth.uid()) AND ((dog_id IS NULL) OR (EXISTS (SELECT 1 FROM dogs d WHERE ((d.id = practice_sessions.dog_id) AND (d.user_id = auth.uid()))))) AND ((enrollment_id IS NULL) OR (EXISTS (SELECT 1 FROM program_enrollments e WHERE ((e.id = practice_sessions.enrollment_id) AND (e.user_id = auth.uid())))))));
create policy practice_sessions_own_select on public.practice_sessions as permissive for select to authenticated using (((user_id = auth.uid()) OR is_admin()));
create policy profiles_delete_super_admin on public.profiles as permissive for delete to authenticated using (is_super_admin());
create policy profiles_insert_own on public.profiles as permissive for insert to authenticated with check (((user_id = auth.uid()) AND (role = 'client'::app_role)));
create policy profiles_select_own_or_admin on public.profiles as permissive for select to authenticated using (((user_id = auth.uid()) OR is_admin()));
create policy profiles_update_own_or_admin on public.profiles as permissive for update to authenticated using (((user_id = auth.uid()) OR is_admin())) with check (((user_id = auth.uid()) OR is_admin()));
create policy program_attendances_admin_delete on public.program_attendances as permissive for delete to authenticated using (is_admin());
create policy program_attendances_admin_insert on public.program_attendances as permissive for insert to authenticated with check (is_admin());
create policy program_attendances_admin_update on public.program_attendances as permissive for update to authenticated using (is_admin()) with check (is_admin());
create policy program_attendances_select_own_or_admin on public.program_attendances as permissive for select to authenticated using ((EXISTS (SELECT 1 FROM program_enrollments pe WHERE ((pe.id = program_attendances.enrollment_id) AND ((pe.user_id = auth.uid()) OR is_admin())))));
create policy program_class_cancellations_admin_delete on public.program_class_cancellations as permissive for delete to authenticated using ((EXISTS (SELECT 1 FROM profiles p WHERE ((p.user_id = auth.uid()) AND (p.role = ANY (ARRAY['admin'::app_role, 'super_admin'::app_role]))))));
create policy program_class_cancellations_admin_insert on public.program_class_cancellations as permissive for insert to authenticated with check ((EXISTS (SELECT 1 FROM profiles p WHERE ((p.user_id = auth.uid()) AND (p.role = ANY (ARRAY['admin'::app_role, 'super_admin'::app_role]))))));
create policy program_class_cancellations_admin_update on public.program_class_cancellations as permissive for update to authenticated using ((EXISTS (SELECT 1 FROM profiles p WHERE ((p.user_id = auth.uid()) AND (p.role = ANY (ARRAY['admin'::app_role, 'super_admin'::app_role])))))) with check ((EXISTS (SELECT 1 FROM profiles p WHERE ((p.user_id = auth.uid()) AND (p.role = ANY (ARRAY['admin'::app_role, 'super_admin'::app_role]))))));
create policy program_class_cancellations_public_calendar_select on public.program_class_cancellations as permissive for select to anon, authenticated using ((restored_at IS NULL));
create policy program_class_cancellations_public_select on public.program_class_cancellations as permissive for select to anon, authenticated using ((restored_at IS NULL));
create policy program_enrollments_admin_insert on public.program_enrollments as permissive for insert to authenticated with check (is_admin());
create policy program_enrollments_admin_update on public.program_enrollments as permissive for update to authenticated using (is_admin()) with check (is_admin());
create policy program_enrollments_select_own_or_admin on public.program_enrollments as permissive for select to authenticated using (((user_id = auth.uid()) OR is_admin()));
create policy program_enrollments_super_admin_delete on public.program_enrollments as permissive for delete to authenticated using (is_super_admin());
create policy program_exams_admin_all on public.program_exams as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy program_exams_owner_insert_enabled on public.program_exams as permissive for insert to authenticated with check ((is_feature_enabled('exams'::text) AND (requested_by = auth.uid()) AND (status = 'requested'::text) AND (EXISTS (SELECT 1 FROM program_enrollments e WHERE ((e.id = program_exams.enrollment_id) AND (e.user_id = auth.uid()))))));
create policy program_exams_owner_select_enabled on public.program_exams as permissive for select to authenticated using ((is_feature_enabled('exams'::text) AND (EXISTS (SELECT 1 FROM program_enrollments e WHERE ((e.id = program_exams.enrollment_id) AND (e.user_id = auth.uid()))))));
create policy program_schedule_versions_admin_write on public.program_schedule_versions as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy program_schedule_versions_read on public.program_schedule_versions as permissive for select to public using (true);
create policy program_schedules_admin_all on public.program_schedules as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy program_schedules_public_calendar_select on public.program_schedules as permissive for select to anon, authenticated using ((is_active = true));
create policy program_schedules_select_active_or_admin on public.program_schedules as permissive for select to authenticated using ((is_active OR is_admin()));
create policy program_sessions_admin_all on public.program_sessions as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy program_sessions_authenticated_select on public.program_sessions as permissive for select to authenticated using (true);
create policy programs_admin_all on public.programs as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy programs_public_calendar_select on public.programs as permissive for select to anon, authenticated using ((is_active = true));
create policy programs_select_active_or_admin on public.programs as permissive for select to authenticated using ((is_active OR is_admin()));
create policy user_achievements_admin_all on public.user_achievements as permissive for all to authenticated using (is_admin()) with check (is_admin());
create policy user_achievements_select_own_or_admin on public.user_achievements as permissive for select to authenticated using (((user_id = auth.uid()) OR is_admin()));
