-- Effective table grants, grouped by table and role.
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.achievement_definitions to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.achievement_definitions to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.achievement_definitions to service_role;
grant INSERT, SELECT on table public.admin_audit_logs to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.admin_audit_logs to service_role;
grant SELECT on table public.announcements to anon;
grant DELETE, INSERT, SELECT, UPDATE on table public.announcements to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.announcements to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.attendance_qr_codes to anon;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.attendance_qr_codes to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.attendance_qr_codes to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.dog_documents to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.dog_documents to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.dog_documents to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.dogs to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.dogs to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.dogs to service_role;
grant SELECT on table public.events to anon;
grant DELETE, INSERT, SELECT, UPDATE on table public.events to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.events to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.feature_flags to anon;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.feature_flags to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.feature_flags to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.member_visits to anon;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.member_visits to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.member_visits to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.membership_billing_profiles to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.membership_billing_profiles to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.membership_billing_profiles to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.membership_delete_requests to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.membership_delete_requests to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.membership_delete_requests to service_role;
grant DELETE, INSERT, SELECT, UPDATE on table public.memberships to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.memberships to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.notification_campaigns to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.notification_campaigns to authenticated;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.notification_campaigns to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.notification_class_cancellation_locks to anon;
grant REFERENCES, TRIGGER, TRUNCATE on table public.notification_class_cancellation_locks to authenticated;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.notification_class_cancellation_locks to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.notification_class_reminder_locks to anon;
grant REFERENCES, TRIGGER, TRUNCATE on table public.notification_class_reminder_locks to authenticated;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.notification_class_reminder_locks to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.notification_deliveries to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.notification_deliveries to authenticated;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.notification_deliveries to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.notification_preferences to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.notification_preferences to authenticated;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.notification_preferences to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.notification_tokens to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.notification_tokens to authenticated;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.notification_tokens to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.payment_obligations to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.payment_obligations to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.payment_obligations to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.payment_settings to anon;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.payment_settings to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.payment_settings to service_role;
grant DELETE, INSERT, SELECT, UPDATE on table public.payments to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.payments to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.practice_sessions to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.practice_sessions to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.practice_sessions to service_role;
grant DELETE, INSERT, SELECT, UPDATE on table public.profiles to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.profiles to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.program_attendances to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.program_attendances to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.program_attendances to service_role;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.program_class_cancellations to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.program_class_cancellations to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.program_class_cancellations to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.program_enrollments to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.program_enrollments to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.program_enrollments to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.program_exams to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.program_exams to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.program_exams to service_role;
grant SELECT on table public.program_schedule_versions to anon;
grant SELECT on table public.program_schedule_versions to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.program_schedule_versions to service_role;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.program_schedules to anon;
grant INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.program_schedules to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.program_schedules to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.program_sessions to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.program_sessions to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.program_sessions to service_role;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.programs to anon;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.programs to authenticated;
grant REFERENCES, SELECT, TRIGGER, TRUNCATE on table public.programs to service_role;
grant REFERENCES, TRIGGER, TRUNCATE on table public.user_achievements to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on table public.user_achievements to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE on table public.user_achievements to service_role;
