export const ucapsaBrand = {
  name: 'UCAPSA',
  slogan: 'La universidad de tu perro',
  colors: {
    red: '#C91F37',
    redDark: '#8F1324',
    redSoft: '#FFE8EC',
    blue: '#2563EB',
    blueDark: '#1D4ED8',
    blueSoft: '#EAF1FF',
    gold: '#FACC15',
    goldDark: '#92400E',
    goldSoft: '#FFF7CC',
    green: '#0f766e',
    greenDark: '#134e4a',
    greenSoft: '#ccfbf1',
    slate: '#0f172a',
    background: '#FFF8F8',
    surface: '#FFFFFF',
    surfaceAlt: '#FFF1F3',
    border: '#F0D4DA',
    text: '#25151A',
    muted: '#70545E',
    success: '#157347',
    warning: '#A35A00',
    danger: '#991b1b',
  },
  socialLinks: [
    { key: 'whatsapp', label: 'WhatsApp', url: 'https://wa.me/525522410679', icon: 'whatsapp' },
    { key: 'website', label: 'Sitio web', url: 'https://www.ucapsa.mx', icon: 'web' },
    { key: 'facebook', label: 'Facebook', url: 'https://www.facebook.com/UCAPSA/', icon: 'facebook' },
    { key: 'instagram', label: 'Instagram', url: 'https://www.instagram.com/byucapsa/', icon: 'instagram' },
    { key: 'x', label: 'X', url: 'https://x.com/ucapsa', icon: 'twitter' },
  ] as const,
};
