-- Make permanent QR identity database-owned.
--
-- Memberships already use gen_random_uuid() as the qr_token default.
-- Program enrollments now do the same so clients never need to generate an
-- authorization-bearing QR token with Math.random().

alter table public.program_enrollments
  alter column qr_token set default (gen_random_uuid())::text;

comment on column public.program_enrollments.qr_token is
  'Permanent program QR token generated by PostgreSQL; clients must not invent this token.';
